/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nano.swig;

public class CTest {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CTest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CTest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanoJNIJNI.delete_CTest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConstructor(SWIGTYPE_p_f_p_CTest__void value) {
    NanoJNIJNI.CTest_constructor_set(swigCPtr, SWIGTYPE_p_f_p_CTest__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_CTest__void getConstructor() {
    long cPtr = NanoJNIJNI.CTest_constructor_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_CTest__void(cPtr, false);
  }

  public void setData(double value) {
    NanoJNIJNI.CTest_data_set(swigCPtr, value);
  }

  public double getData() {
    return NanoJNIJNI.CTest_data_get(swigCPtr);
  }

  public void setGetSum(SWIGTYPE_p_f_p_CTest_double__double value) {
    NanoJNIJNI.CTest_getSum_set(swigCPtr, SWIGTYPE_p_f_p_CTest_double__double.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_CTest_double__double getGetSum() {
    long cPtr = NanoJNIJNI.CTest_getSum_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_CTest_double__double(cPtr, false);
  }

  public void setGetTest(SWIGTYPE_p_f_p_CTest_double_double__double value) {
    NanoJNIJNI.CTest_getTest_set(swigCPtr, SWIGTYPE_p_f_p_CTest_double_double__double.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_CTest_double_double__double getGetTest() {
    long cPtr = NanoJNIJNI.CTest_getTest_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_CTest_double_double__double(cPtr, false);
  }

  public CTest() {
    this(NanoJNIJNI.new_CTest(), true);
  }

}
