/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nano.swig;

public class MultiLinkElement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MultiLinkElement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiLinkElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanoJNIJNI.delete_MultiLinkElement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLinkcount(int value) {
    NanoJNIJNI.MultiLinkElement_linkcount_set(swigCPtr, this, value);
  }

  public int getLinkcount() {
    return NanoJNIJNI.MultiLinkElement_linkcount_get(swigCPtr, this);
  }

  public void setPrev(SWIGTYPE_p_p_MultiLinkElement value) {
    NanoJNIJNI.MultiLinkElement_prev_set(swigCPtr, this, SWIGTYPE_p_p_MultiLinkElement.getCPtr(value));
  }

  public SWIGTYPE_p_p_MultiLinkElement getPrev() {
    long cPtr = NanoJNIJNI.MultiLinkElement_prev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_MultiLinkElement(cPtr, false);
  }

  public void setNext(SWIGTYPE_p_p_MultiLinkElement value) {
    NanoJNIJNI.MultiLinkElement_next_set(swigCPtr, this, SWIGTYPE_p_p_MultiLinkElement.getCPtr(value));
  }

  public SWIGTYPE_p_p_MultiLinkElement getNext() {
    long cPtr = NanoJNIJNI.MultiLinkElement_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_MultiLinkElement(cPtr, false);
  }

  public void set_final(SWIGTYPE_p_f_p_MultiLinkElement__void value) {
    NanoJNIJNI.MultiLinkElement__final_set(swigCPtr, this, SWIGTYPE_p_f_p_MultiLinkElement__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_MultiLinkElement__void get_final() {
    long cPtr = NanoJNIJNI.MultiLinkElement__final_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_MultiLinkElement__void(cPtr, false);
  }

  public void setFree(SWIGTYPE_p_f_p_MultiLinkElement__p_MultiLinkElement value) {
    NanoJNIJNI.MultiLinkElement_free_set(swigCPtr, this, SWIGTYPE_p_f_p_MultiLinkElement__p_MultiLinkElement.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_MultiLinkElement__p_MultiLinkElement getFree() {
    long cPtr = NanoJNIJNI.MultiLinkElement_free_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_MultiLinkElement__p_MultiLinkElement(cPtr, false);
  }

  public void setClear(SWIGTYPE_p_f_p_MultiLinkElement__void value) {
    NanoJNIJNI.MultiLinkElement_clear_set(swigCPtr, this, SWIGTYPE_p_f_p_MultiLinkElement__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_MultiLinkElement__void getClear() {
    long cPtr = NanoJNIJNI.MultiLinkElement_clear_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_MultiLinkElement__void(cPtr, false);
  }

  public MultiLinkElement() {
    this(NanoJNIJNI.new_MultiLinkElement(), true);
  }

}
