/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nano.swig;

public interface NanoJNIConstants {
  public final static int MAP_SHIFT = NanoJNIJNI.MAP_SHIFT_get();
  public final static int POOL_MAX = NanoJNIJNI.POOL_MAX_get();
  public final static int MAP_MAX = NanoJNIJNI.MAP_MAX_get();
  public final static int MAP_MASK = NanoJNIJNI.MAP_MASK_get();
}
