/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nano.swig;

public class Word {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Word(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Word obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NanoJNIJNI.delete_Word(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnglish(String value) {
    NanoJNIJNI.Word_english_set(swigCPtr, this, value);
  }

  public String getEnglish() {
    return NanoJNIJNI.Word_english_get(swigCPtr, this);
  }

  public void setWord_class(String value) {
    NanoJNIJNI.Word_word_class_set(swigCPtr, this, value);
  }

  public String getWord_class() {
    return NanoJNIJNI.Word_word_class_get(swigCPtr, this);
  }

  public void setChinese(String value) {
    NanoJNIJNI.Word_chinese_set(swigCPtr, this, value);
  }

  public String getChinese() {
    return NanoJNIJNI.Word_chinese_get(swigCPtr, this);
  }

  public void setExample(String value) {
    NanoJNIJNI.Word_example_set(swigCPtr, this, value);
  }

  public String getExample() {
    return NanoJNIJNI.Word_example_get(swigCPtr, this);
  }

  public void setEnglish_inv(String value) {
    NanoJNIJNI.Word_english_inv_set(swigCPtr, this, value);
  }

  public String getEnglish_inv() {
    return NanoJNIJNI.Word_english_inv_get(swigCPtr, this);
  }

  public Word() {
    this(NanoJNIJNI.new_Word(), true);
  }

}
